### PR TITLE
Native code needs JSON representation of Element.

### LINKED ISSUE #919: material and transp are stripped from SubCategory's appearance props
**Describe the bug**
When inserting a new SpatialCategory 
`priCategoryId = SpatialCategory.insert(iModelDb, IModelDb.dictionaryId, "FieldWeld", new SubCategoryAppearance({ material: material.materialId, priority: 100 }));`

**To Reproduce**

1. insert new RenderMaterialElement
2. use that id in a new SubcategoryAppearance

**Expected behavior**
The subcategory appearance can reference

**Screenshots**

**Desktop (please complete the applicable information):**

- OS: [Windows]
- Browser [chrome]
- iTwin.js Version [2.11.0 & 2.12.0]

**Additional context**
Here's some sudo code to debug

`const params: RenderMaterialElement.Params = {
  description: "Field Weld",
  color: [0.9058, 0.298, 0.2352],
  diffuse: 0.5,
  finish: 0.15,
  paletteName: "MyPalette",
  reflectColor: [0.9, 0.3, 0.25],
  specularColor: [0.2, 0.2, 0.2],
};
const fieldWeldId = RenderMaterialElement.insert(iModelDb, IModelDb.dictionaryId, "FieldWeldMaterial", params);
const codeValue = RenderMaterialElement.createCode(iModelDb, IModelDb.dictionaryId, "FieldWeldMaterial");

const materialId = iModel.elements.queryElementIdByCode(RenderMaterialElement.createCode(iModel,IModelDb.dictionaryId, "FieldWeldMaterial"));
if (materialId) {
  const material = iModel.elements.getElement<RenderMaterialElement>(materialId);
  console.log(`render material: ${JSON.stringify(material)}`);
}

const appearance = new SubCategoryAppearance({material: materialId, priority: 100, transp: 0.75});
console.log (`generating subcategory with SubCategoryAppearance.Props ${JSON.stringify(appearance)}`);
priCategoryId = SpatialCategory.insert(iModel, IModelDb.dictionaryId, "FieldWeld", appearance);
console.log(`New CategegoryId: ${priCategoryId}`);

const subCatId = iModel.elements.queryElementIdByCode(SubCategory.createCode(iModel, priCategoryId, "FieldWeld"));
if (subCatId) {
  const subCat = iModel.elements.getElement<SubCategory>(subCatId)
  console.log(`SubCategory Appearance: ${JSON.stringify(subCat)}`);
}
`
the resulting console logs are as follows: (in the last line you will see the appearance had material and transp dropped)

`render material: {
  "classFullName":"BisCore:RenderMaterial",
  "id":"0x20000000005",
  "paletteName":"MyPallette",
  "description":"Field Weld",
  "code":{"spec":"0x1b","scope":"0x10","value":"schemaName:FieldWeldMaterial"},
  "model":"0x10",
  "jsonProperties":{
    "materialAssets":{
      "renderMaterial":{
        "HasBaseColor":true,
        "color":[0.9058, 0.298, 0.2352],
        "HasSpecularColor":true,
        "specular_color":[0.2,0.2,0.2],
        "HasFinish":true,
        "finish":0.15,
        "HasTransmit":false,
        "HasDiffuse":true,
        "diffuse":0.5,
        "HasSpecular":false,
        "HasReflect":false,
        "HasReflectColor":true,
        "reflect_color":[0.9, 0.3, 0.25]
      }
    }
  },
  "isPrivate":false
}

generating subcategory with SubCategoryAppearance.Props {"color":0,"priority":100,"material":"0x20000000005","transp":0.75}

New CategegoryId: 0x20000000014
SubCategory Appearance: {
  "classFullName":"BisCore:SubCategory",
  "id":"0x20000000015",
  "code":{"spec":"0x1e","scope":"0x20000000014","value":"schemaName:FieldWeld"},
  "model":"0x10",
  "parent":{"id":"0x20000000014","relClassName":"BisCore:CategoryOwnsSubCategories"},
  "isPrivate":false,
  "appearance":{"color":0,"priority":100}}`

### PR DESCRIPTION
**Pull request by pmconne**
To fix #919.
In the process of fixing that, it was discovered that Texture.toJSON() was base-64-encoding the image bytes but failing to prepend the "encoding=base64;" prefix required by ECDb. Added Base64EncodedString type and API, and more tests.
Incidentally moved SubCategoryAppearance tests out of imodeljs-backend to imodeljs-common where they belong, and added actual Category tests to imodeljs-backend.
Incidentally made the onInsert/ed, onUpdate/d, and onDelete/d static methods of Element, ElementAspect, and Model take their props arguments are Readonly, since they are supposed only to observe, not mutate.

### CODE REVIEW

**Review by kabentley — APPROVED** [review]

File: core/backend/src/IModelDb.ts [hunk 1]
```diff
@@ -1632,7 +1632,9 @@ export namespace IModelDb { // eslint-disable-line no-redeclare
       const iModel = this._iModel;
       const jsClass = iModel.getJsClass<typeof Element>(elProps.classFullName) as any; // "as any" so we can call the protected methods
       jsClass.onInsert(elProps, iModel);
-      const val = iModel.nativeDb.insertElement(elProps);
+
+      const json = elProps instanceof Element ? elProps.toJSON() : elProps;
+      const val = iModel.nativeDb.insertElement(json);
```
Comment (kabentley) [inline core/backend/src/IModelDb.ts:1637]: really, we should update the id in `json` and pass it to `onInserted` below

Comment (pmconne) [reply core/backend/src/IModelDb.ts:1637]: My concern was that onInsert/ed and onUpdate/d might want to mutate the input.
All of the implementations in imodeljs repo just pull out Ids for concurrency control.

**Comment by pmconne** [comment]
@Mergifyio backport release/2.13.x

File: core/backend/src/IModelDb.ts (hunk 1 above)
Comment (kabentley) [reply core/backend/src/IModelDb.ts:1637]: but they're declared to take an `ElementProps`. They'll potentially have the same problem as insert/update.

Comment (scsewall) [reply core/backend/src/IModelDb.ts:1637]: Shouldn't we correct the mistake where `SubCategoryAppearance` and `SubCategoryAppearance.Props` have different names for the same property? That would not have been intentional. Seems like we could support both names and deprecate one of them...

Comment (pmconne) [reply core/backend/src/IModelDb.ts:1637]: We have several cases where the persistent JSON names do not match the class property names, whether intentional or not. The mistake is in treating Entity and EntityProps as interchangeable.

Comment (pmconne) [reply core/backend/src/IModelDb.ts:1637]: @kabentley made this change and made all the class handlers take `Readonly` props because they are supposed to only react to insert/update/delete, not mutate.

Comment (scsewall) [reply core/backend/src/IModelDb.ts:1637]: The current behavior of `insertElement` is to update the input props.id property. I am sure that things will break if that is changed.

Comment (kabentley) [reply core/backend/src/IModelDb.ts:1637]: it does still update the input value's id property.

Comment (scsewall) [reply core/backend/src/IModelDb.ts:1637]: I still think that trivial differences in names between Elements and ElementProps are confusing and should be corrected. Consistency is good.

Comment (kabentley) [reply core/backend/src/IModelDb.ts:1637]: I agree, it was always a mistake for Entity to "implement" EntityProps. I don't know what we can do without a major version change.

Comment (scsewall) [reply core/backend/src/IModelDb.ts:1637]: BTW, our `ecschema2ts` tool that developers use to generate TypeScript wrapper code automatically adds the `implements *Props` to the classes it generates. If we decide that was a mistake, we would have to correct the `ecschema2ts` tool also.

**Comment by pmconne** [comment]
@kabentley this breaks insertion of Texture elements. Texture.data is a Uint8Array. TextureProps.data is a base64-encoded string. The addon expects to receive a Uint8Array. I think that changed when you stopped stringifying.

File: core/common/src/Base64EncodedString.ts [hunk 2]
```diff
@@ -0,0 +1,65 @@
+/*---------------------------------------------------------------------------------------------
+* Copyright (c) Bentley Systems, Incorporated. All rights reserved.
+* See LICENSE.md in the project root for license terms and full copyright notice.
+*--------------------------------------------------------------------------------------------*/
+/** @packageDocumentation
+ * @module Entities
+ */
+
+/** Represents an array of bytes encoded in base-64 with a prefix indicating the encoding, as persisted in an [ECDb]($backend) for properties of `binary` type.
```
Comment (kabentley) [inline core/common/src/Base64EncodedString.ts:9]: i'm not sure this sentence is right. The property is persisted as binary in the ECDb, but retuned using Base64EncodedString.

File: core/backend/src/Texture.ts [hunk 3]
```diff
@@ -23,27 +33,30 @@ export class Texture extends DefinitionElement {
...
   public flags: TextureFlags;
   public description?: string;
+
   /** @internal */
-  constructor(props: TextureProps & { data: Uint8Array | string }, iModel: IModelDb) {
+  constructor(props: TextureCreateProps, iModel: IModelDb) {
     super(props, iModel);
     this.format = props.format;
-    this.data = (typeof props.data == "string") ? Buffer.from(props.data, "base64") : props.data;
+    this.data = typeof props.data === "string" ? Base64EncodedString.toUint8Array(props.data) : props.data;
```
Comment (kabentley) [inline core/backend/src/Texture.ts:41]: wow, how did that get through our linter?

File: core/common/src/Base64EncodedString.ts (hunk 2 above)
Comment (pmconne) [reply core/common/src/Base64EncodedString.ts:9]: Yeah I'll rephrase.

File: core/backend/src/Texture.ts (hunk 3 above)
Comment (pmconne) [reply core/backend/src/Texture.ts:41]: Maybe it recognizes that comparing `typeof` to `"string"` is always unambiguous, I don't know.

**Review by khanaffan — APPROVED** [review]

File: core/common/src/Base64EncodedString.ts (hunk 2 above)
Comment (pmconne) [reply core/common/src/Base64EncodedString.ts]: Rephrased.
